### Hello World! 
GET http://localhost:3000/api/test/hello

###
GET http://localhost:3000/api/assets

###
POST http://localhost:3000/api/assets
Content-Type: application/json

{
    "id": "asset_01",
    "symbol": "A1"
}

###
GET http://localhost:3000/api/orders


###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "asset_id": "asset_01",
  "price": 2000
}