version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000 # application
      - 5555:5555 # prisma studio
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: bitnami/mongodb:5.0.17
    volumes:
      - hiokdev_mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest

volumes:
  hiokdev_mongodb_data:
    driver: local
